import type { CompasTask } from './types';

export const LIFE_AREAS = [
  'cuerpo',
  'entorno',
  'mente',
  'conexion',
  'crecimiento',
] as const;

export const COMPAS_SEED_TASKS: CompasTask[] = [
  {
    slug: 'hacer-la-cama',
    name: 'Hacer la cama',
    category: 'orden',
    lifeArea: 'entorno',
    benefits: ['Orden visual inmediato', 'Primera victoria del dia'],
    activationEnergy: 'low',
    durationSeconds: 300,
    psychologicalReward: 'immediate',
    toltecAgreement: 'se-impecable-con-tus-palabras',
    isSeed: true,
    sortOrder: 10,
  },
  {
    slug: 'lavar-3-platos',
    name: 'Lavar 3 platos',
    category: 'orden',
    lifeArea: 'entorno',
    benefits: ['Tarea mecanica breve', 'Reduce ruido visual'],
    activationEnergy: 'low',
    durationSeconds: 300,
    psychologicalReward: 'immediate',
    toltecAgreement: 'no-hagas-suposiciones',
    isSeed: true,
    sortOrder: 20,
  },
  {
    slug: 'despejar-un-metro',
    name: 'Despejar 1 metro cuadrado',
    category: 'orden',
    lifeArea: 'entorno',
    benefits: ['Hace visible el avance', 'Recupera control del espacio'],
    activationEnergy: 'medium',
    durationSeconds: 600,
    psychologicalReward: 'immediate',
    toltecAgreement: 'haz-siempre-lo-maximo-que-puedas',
    isSeed: true,
    sortOrder: 30,
  },
  {
    slug: 'beber-agua',
    name: 'Beber un vaso de agua',
    category: 'cuidado',
    lifeArea: 'cuerpo',
    benefits: ['Activacion fisica basica', 'Senal de cuidado inmediato'],
    activationEnergy: 'low',
    durationSeconds: 60,
    psychologicalReward: 'immediate',
    toltecAgreement: 'haz-siempre-lo-maximo-que-puedas',
    isSeed: true,
    sortOrder: 40,
  },
  {
    slug: 'ducha-reinicio',
    name: 'Ducha de reinicio',
    category: 'cuidado',
    lifeArea: 'cuerpo',
    benefits: ['Cambio de estado fisico', 'Reset emocional sin juicio'],
    activationEnergy: 'low',
    durationSeconds: 900,
    psychologicalReward: 'immediate',
    toltecAgreement: 'no-te-tomes-nada-personalmente',
    isSeed: true,
    sortOrder: 50,
  },
  {
    slug: 'caminar-esquina',
    name: 'Caminar a la esquina',
    category: 'movimiento',
    lifeArea: 'cuerpo',
    benefits: ['Luz y movimiento', 'Rompe encierro y postura sedentaria'],
    activationEnergy: 'medium',
    durationSeconds: 600,
    psychologicalReward: 'immediate',
    toltecAgreement: 'haz-siempre-lo-maximo-que-puedas',
    isSeed: true,
    sortOrder: 60,
  },
  {
    slug: 'respirar-4-7-8',
    name: 'Respirar 4-7-8',
    category: 'regulacion',
    lifeArea: 'mente',
    benefits: ['Calma el sistema nervioso', 'Interrumpe rumiacion'],
    activationEnergy: 'low',
    durationSeconds: 180,
    psychologicalReward: 'immediate',
    toltecAgreement: 'no-hagas-suposiciones',
    isSeed: true,
    sortOrder: 70,
  },
  {
    slug: 'escribir-idea-libre',
    name: 'Escribir 1 idea libre',
    category: 'descarga',
    lifeArea: 'mente',
    benefits: ['Saca pensamientos de la cabeza', 'Reduce ansiedad difusa'],
    activationEnergy: 'low',
    durationSeconds: 300,
    psychologicalReward: 'immediate',
    toltecAgreement: 'no-te-tomes-nada-personalmente',
    isSeed: true,
    sortOrder: 80,
  },
  {
    slug: 'ordenar-proxima-accion',
    name: 'Escribir la proxima accion',
    category: 'claridad',
    lifeArea: 'mente',
    benefits: ['Convierte niebla en paso concreto', 'Reduce friccion de inicio'],
    activationEnergy: 'medium',
    durationSeconds: 300,
    psychologicalReward: 'delayed',
    toltecAgreement: 'se-impecable-con-tus-palabras',
    isSeed: true,
    sortOrder: 90,
  },
  {
    slug: 'enviar-hola',
    name: 'Enviar un hola',
    category: 'vinculo',
    lifeArea: 'conexion',
    benefits: ['Mantiene vinculo sin presion', 'Activa amabilidad pequena'],
    activationEnergy: 'medium',
    durationSeconds: 120,
    psychologicalReward: 'immediate',
    toltecAgreement: 'se-impecable-con-tus-palabras',
    isSeed: true,
    sortOrder: 100,
  },
  {
    slug: 'agradecer-a-alguien',
    name: 'Agradecer a alguien',
    category: 'vinculo',
    lifeArea: 'conexion',
    benefits: ['Refuerza una relacion', 'Cambia el foco hacia gratitud'],
    activationEnergy: 'low',
    durationSeconds: 180,
    psychologicalReward: 'immediate',
    toltecAgreement: 'se-impecable-con-tus-palabras',
    isSeed: true,
    sortOrder: 110,
  },
  {
    slug: 'mandar-audio-corto',
    name: 'Mandar un audio corto',
    category: 'vinculo',
    lifeArea: 'conexion',
    benefits: ['Contacto humano breve', 'Evita sobrepensar un mensaje perfecto'],
    activationEnergy: 'medium',
    durationSeconds: 180,
    psychologicalReward: 'immediate',
    toltecAgreement: 'haz-siempre-lo-maximo-que-puedas',
    isSeed: true,
    sortOrder: 120,
  },
  {
    slug: 'leer-una-pagina',
    name: 'Leer 1 pagina',
    category: 'aprendizaje',
    lifeArea: 'crecimiento',
    benefits: [
      'Rompe el bloqueo ante libros largos',
      'Nutre curiosidad sin presion',
    ],
    activationEnergy: 'low',
    durationSeconds: 300,
    psychologicalReward: 'delayed',
    toltecAgreement: 'no-hagas-suposiciones',
    isSeed: true,
    sortOrder: 130,
  },
  {
    slug: 'ver-tutorial-cinco-minutos',
    name: 'Ver 5 minutos de un tutorial',
    category: 'aprendizaje',
    lifeArea: 'crecimiento',
    benefits: ['Aprendizaje pequeno', 'Reduce la barrera de estudiar'],
    activationEnergy: 'low',
    durationSeconds: 300,
    psychologicalReward: 'delayed',
    toltecAgreement: 'haz-siempre-lo-maximo-que-puedas',
    isSeed: true,
    sortOrder: 140,
  },
  {
    slug: 'practicar-quince-minutos',
    name: 'Practicar 15 minutos',
    category: 'aprendizaje',
    lifeArea: 'crecimiento',
    benefits: ['Convierte intencion en repeticion', 'Acumula progreso visible'],
    activationEnergy: 'high',
    durationSeconds: 900,
    psychologicalReward: 'delayed',
    toltecAgreement: 'se-impecable-con-tus-palabras',
    isSeed: true,
    sortOrder: 150,
  },
];
