import { getPotMetadataPrompt } from './prompts/pot-metadata.ts';

/**
 * Structured metadata extracted from pot description
 */
export interface PotMetadata {
  name?: string;
  species?: string;
  seed_type?: string;
  notes?: string;
}

/**
 * Configuration for Gemini API calls
 */
export interface GeminiConfig {
  apiKey: string;
  modelName?: string;
}

/**
 * Error thrown when Gemini API returns an error
 */
export class GeminiAPIError extends Error {
  constructor(
    message: string,
    public status?: number,
    public responseText?: string,
  ) {
    super(message);
    this.name = 'GeminiAPIError';
  }
}

/**
 * Extract structured pot metadata from a user's transcript
 *
 * @param transcript - User's description of the pot/plant
 * @param config - Gemini API configuration
 * @returns Structured metadata extracted from the transcript
 * @throws {GeminiAPIError} When the Gemini API returns an error
 * @throws {Error} When JSON parsing fails or no content is generated
 *
 * @example
 * ```typescript
 * const metadata = await extractPotMetadata(
 *   "Un tomate cherry rojo en maceta pequeña",
 *   { apiKey: process.env.GEMINI_API_KEY }
 * );
 * console.log(metadata.species); // "Tomato"
 * ```
 */
export async function extractPotMetadata(
  transcript: string,
  config: GeminiConfig,
): Promise<PotMetadata> {
  const modelName = config.modelName || 'gemini-flash-latest';
  const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${config.apiKey}`;

  const prompt = getPotMetadataPrompt(transcript);

  const response = await fetch(geminiUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        response_mime_type: 'application/json',
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new GeminiAPIError(
      `Gemini API error: ${response.status}`,
      response.status,
      errorText,
    );
  }

  const data = await response.json();
  const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    throw new Error('No content generated by Gemini API');
  }

  const metadata: PotMetadata = JSON.parse(generatedText);
  return metadata;
}
