import { getIdentifySpeciesPrompt } from './prompts/identify-species.ts';
import { GeminiConfig, GeminiAPIError } from './extract-pot-metadata.ts';

/**
 * Lightweight identification result containing only basic plant identifiers
 */
export interface PlantIdentification {
  species?: string;
  common_name?: string;
  confidence?: 'high' | 'medium' | 'low';
}

/**
 * JSON Schema for PlantIdentification
 */
export const PLANT_IDENTIFICATION_SCHEMA = {
  type: 'object',
  properties: {
    species: {
      type: 'string',
      description:
        'Botanical/scientific species name (e.g., "Solanum lycopersicum", "Monstera deliciosa")',
    },
    common_name: {
      type: 'string',
      description:
        'Common name of the plant (e.g., "Tomato", "Swiss Cheese Plant")',
    },
    confidence: {
      type: 'string',
      enum: ['high', 'medium', 'low'],
      description: 'Confidence level of the identification',
    },
  },
} as const;

/**
 * Lightweight plant species identification to minimize token usage.
 * Use this before extractPotMetadata to check if species info already exists in your database.
 *
 * Cost comparison:
 * - identifyPlantSpecies: ~100-150 tokens
 * - extractPotMetadata: ~1500-2500 tokens
 *
 * Recommended flow:
 * 1. identifyPlantSpecies(transcript)
 * 2. Query database for species metadata
 * 3. If found: merge with user's personal data (name, location, etc.)
 * 4. If NOT found: extractPotMetadata(transcript) for full extraction
 *
 * @param transcript - User's description of the plant
 * @param config - Gemini API configuration
 * @returns Basic plant identification
 * @throws {GeminiAPIError} When the Gemini API returns an error
 *
 * @example
 * ```typescript
 * const id = await identifyPlantSpecies("Un tomate cherry", { apiKey: KEY });
 * console.log(id.species); // "Solanum lycopersicum"
 * console.log(id.common_name); // "Cherry Tomato"
 *
 * // Check if we have metadata for this species
 * const cached = await db.query('SELECT * FROM plant_species WHERE species = ?', [id.species]);
 * if (cached) {
 *   return cached; // Saved ~2000 tokens!
 * }
 * ```
 */
export async function identifyPlantSpecies(
  transcript: string,
  config: GeminiConfig,
): Promise<PlantIdentification> {
  const modelName = config.modelName || 'gemini-flash-latest';
  const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${config.apiKey}`;

  const prompt = getIdentifySpeciesPrompt(transcript);

  const response = await fetch(geminiUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        response_mime_type: 'application/json',
        responseSchema: PLANT_IDENTIFICATION_SCHEMA,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new GeminiAPIError(
      `Gemini API error: ${response.status}`,
      response.status,
      errorText,
    );
  }

  const data = await response.json();
  const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    throw new Error('No content generated by Gemini API');
  }

  const identification: PlantIdentification = JSON.parse(generatedText);
  return identification;
}
