import { supabase } from './supabase';

/**
 * Generates a share code to link accounts in Potlink.
 * @returns {Promise<string | null>} The 6-character share code, or null if an error occurred.
 */
export async function generateShareCode(): Promise<string | null> {
  try {
    const { data, error } = await supabase.rpc('generate_potlink_share_code');

    if (error) {
      console.error('Error generating share code:', error);
      return null;
    }

    return data as string | null;
  } catch (err) {
    console.error('Exception in generateShareCode:', err);
    return null;
  }
}

/**
 * Links the current user's account with the account that generated the share code.
 * @param shareCode The 6-character share code generated by another user
 * @returns {Promise<{success: boolean; error?: string}>} An object containing the success status and an optional error message.
 */
export async function linkAccount(
  shareCode: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const { data, error } = await supabase.rpc('link_potlink_account', {
      share_code: shareCode,
    });

    if (error) {
      console.error('Error linking account:', error);
      return { success: false, error: error.message };
    }

    return { success: !!data };
  } catch (err: any) {
    console.error('Exception in linkAccount:', err);
    return {
      success: false,
      error: err.message || 'Error al vincular cuenta.',
    };
  }
}

/**
 * Retrieves the list of currently linked accounts for the user.
 * We fetch the links where the user_id is the current user.
 * Then we can get some basic info about the linked user (we might need a view or a join with profiles later if we want the actual name).
 * For now, we will just return the linked UUIDs.
 */
export async function getLinkedAccounts(): Promise<
  { linked_user_id: string; created_at: string }[]
> {
  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return [];

    const { data, error } = await supabase
      .from('potlink_account_links')
      .select('linked_user_id, created_at')
      .eq('user_id', user.id);

    if (error) {
      console.error('Error fetching linked accounts:', error);
      return [];
    }

    return data || [];
  } catch (err) {
    console.error('Exception in getLinkedAccounts:', err);
    return [];
  }
}
