import { supabase } from './supabase';

/**
 * Generates a share code to link accounts in Potlink.
 * @returns {Promise<string | null>} The 6-character share code, or null if an error occurred.
 */
export async function generateShareCode(): Promise<string | null> {
  try {
    const { data, error } = await supabase.rpc('generate_potlink_share_code');

    if (error) {
      console.error('Error generating share code:', error);
      return null;
    }

    return data as string | null;
  } catch (err) {
    console.error('Exception in generateShareCode:', err);
    return null;
  }
}

/**
 * Links the current user's account with the account that generated the share code.
 * @param shareCode The 6-character share code generated by another user
 * @returns {Promise<{success: boolean; error?: string}>} An object containing the success status and an optional error message.
 */
export async function linkAccount(
  shareCode: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const { data, error } = await supabase.rpc('link_potlink_account', {
      share_code: shareCode,
    });

    if (error) {
      console.error('Error linking account:', error);
      return { success: false, error: error.message };
    }

    return { success: !!data };
  } catch (err: any) {
    console.error('Exception in linkAccount:', err);
    return {
      success: false,
      error: err.message || 'Error al vincular cuenta.',
    };
  }
}

export interface LinkedAccount {
  linked_user_id: string;
  email: string | null;
  name: string | null;
  created_at: string;
}

/**
 * Retrieves the list of currently linked accounts for the user, including name and email.
 */
export async function getLinkedAccounts(): Promise<LinkedAccount[]> {
  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return [];

    // Use RPC to securely fetch linked user details (name, email)
    const { data, error } = await supabase.rpc(
      'get_potlink_linked_accounts_info',
    );

    if (error) {
      console.error('Error fetching linked accounts info:', error);
      return [];
    }

    return (data as LinkedAccount[]) || [];
  } catch (err) {
    console.error('Exception in getLinkedAccounts:', err);
    return [];
  }
}

/**
 * Unlinks the current user's account from the specified linked user.
 * @param linkedUserId The user ID of the account to unlink
 * @returns {Promise<{success: boolean; error?: string}>} An object containing the success status and an optional error message.
 */
export async function unlinkAccount(
  linkedUserId: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return { success: false, error: 'User not authenticated' };

    const { error } = await supabase
      .from('potlink_account_links')
      .delete()
      .eq('user_id', user.id)
      .eq('linked_user_id', linkedUserId);

    if (error) {
      console.error('Error unlinking account:', error);
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (err: any) {
    console.error('Exception in unlinkAccount:', err);
    return {
      success: false,
      error: err.message || 'Error al desvincular cuenta.',
    };
  }
}
